version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    ports:
      - "3400:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
