version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    ports:
      - "3401:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password


volumes:
  mysql_data:
